# Generated by Django 5.1.5 on 2025-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+ Positive'), ('AB+', 'AB+ Positive'), ('B+', 'B+ Positive'), ('O+', 'O+ Positive')], max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
