# Generated by Django 5.1.5 on 2025-01-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='blood_group',
            field=models.CharField(max_length=50),
        ),
    ]
