# Generated by Django 5.1.5 on 2025-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_usersmodel_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
