# Generated by Django 5.1.5 on 2025-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_usersmodel_groups_usersmodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
