# Generated by Django 5.1.5 on 2025-02-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_usersmodel_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
