# Generated by Django 5.1.5 on 2025-02-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_usersmodel_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='division',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='upazila',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='user',
        ),
    ]
