# Generated by Django 5.1.5 on 2025-02-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_userprofiles_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodel',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
