# Generated by Django 4.2.13 on 2024-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('blood_group', models.IntegerField(choices=[('A', 'A+ (Positive)'), ('A-', 'A- (Negitive)'), ('B+', 'B+ (Positive)'), ('B-', 'B- (Negitive)'), ('AB+', 'AB+ (Negitive)'), ('O+', 'O+ (Positive)'), ('O-', 'O- (Negitive)')])),
                ('total_donated', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
