# Generated by Django 4.2.13 on 2024-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A+ (Positive)'), ('A-', 'A- (Negitive)'), ('B+', 'B+ (Positive)'), ('B-', 'B- (Negitive)'), ('AB+', 'AB+ (Negitive)'), ('O+', 'O+ (Positive)'), ('O-', 'O- (Negitive)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donator',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
