# Generated by Django 4.2.13 on 2024-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0004_donatordetails_delete_donator'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatordetails',
            name='age',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='donatordetails',
            name='full_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='donatordetails',
            name='total_donated',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
