# Generated by Django 4.2.13 on 2024-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0005_donatordetails_age_donatordetails_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatordetails',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='donatordetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donatordetails',
            name='total_donated',
            field=models.IntegerField(default=0),
        ),
    ]
